### ISSUE TITLE
Versioning Assets (using `grunt.template.today`)

### ISSUE THREAD

**Issue by LeoAdamek** [dciccale/grunt-processhtml#10]
Hi,

If I were to have the following other Grunt tasks before `processhtml`

* `src/coffee/**/*.coffee` → `/js/application-<%= grunt.template.today(format) %>.min.js`

* `src/less/**/*.less` → `/css/application-<%= grunt.template.today(format) %>.min.css`

How could I get `processhtml` to use the versioned asset file names? (e.g. `/css/application-20131120110505.min.css`

**Comment by dciccale** [comment]
Sorry for delay on this, I guess that versioning could be done a part from this plugin. However I am open to PRs.

@lgelfan that's actually a pretty good solution to use right away without implementing it inside the plugin.

@LeoAdamek take a look at that, could help

**Comment by SiamKreative** [comment]
What if I would like to add the version like that: `build:css css/styles.min.css?v=1.0.7`, instead of versioning the assets themselves. How could I implement this?

**Comment by dciccale** [comment]
You can do that already.

```html
<!-- build:css test.css?v=1.0 -->
<link type="stylesheet" href="dev/test.css">
<!-- /build -->
```

will output:

```html
<link rel="stylesheet" href="test.css?v=1.0">
```

**Comment by dciccale** [comment]
moving discussion to here https://github.com/dciccale/node-htmlprocessor/pull/17
