### ISSUE TITLE
comment/uncomment code blocks

### ISSUE THREAD

**Issue by vlrprbttst** [dciccale/grunt-processhtml#103]
I use processhtml to embed critical css. The problem I have is I only want it to be inlined on my build process, but have it removed while on dev.

my gruntfile.js looks like this:

```
        processhtml: {
            dev: {
                files: [{
                    expand: true,
                    cwd: '<%= source %>/',
                    src: ['**/*.html'],
                    dest: '<%= dev %>/',
                    ext: '.html'
                }, ],
            },
            build: {
                files: [{
                    expand: true,
                    cwd: '<%= dev %>/',
                    src: ['**/*.html'],
                    dest: '<%= site %>/',
                    ext: '.html'
                }, ],
            }
        },
```

from my source folder i have

```
<!-- build:css:build inline -->
<link rel="stylesheet" href="../_dev/critical-css/index.css">
<!-- /build -->
```

and this works, but I would need an intermediate state where in DEV i have that line commented, and in DIST to be uncommented and inlined.

I doubt I was clear but I hope you get it. you can find the full thing here to better understand: https://github.com/vlrprbttst/BoxTent

Is there a way to achieve this? maybe via a comment/uncomment option or a template?
thanks! :)

**Comment by dciccale** [comment]
run `grunt processhtml:dev` to only target dev

**Comment by dciccale** [comment]
so, i checked your repo. 

add another block in your html

```
<!-- build:css:dev -->
<link rel="stylesheet" href="../_dev/critical-css/index.css">
<!-- /build -->
```

with `dev` target, and without `inline`
