### ISSUE TITLE
Done without errors but no file produced

### ISSUE THREAD

**Issue by Romkond** [dciccale/grunt-processhtml#104]
Hi. I've got my .htm files in dist directory. Gruntfile chunk is:
`processhtml: {
      build: {
            files: {
                'dist/home.htm' : ['new_home.htm']
            }
        }
},`
Home.htm is 
```
<!-- base href="http://forscrap.com/" -->
<!-- build:css dist/compiled.css -->
<link rel="stylesheet" type="text/css" href="Home_files/bootstrap.css">
<link rel="stylesheet" type="text/css" href="Home_files/style.css">
<link rel="stylesheet" type="text/css" href="Home_files/font-awesome.css">
<!-- /build -->
```
I run grunt processhtml and get

> Running "processhtml:build" (processhtml) task
> Done, without errors.

but there's no new_home.htm anywhere. WTH? Thanx.

**Comment by dciccale** [comment]
`processhtml: { build: { files: { 'dist/home.htm' : ['new_home.htm'] } } }`

the files directive is `output: [input]` so if your files are IN the `dist` dir, you should give grunt this way:

`processhtml: { build: { files: { 'some_other_folder/home.htm' : ['dist/new_home.htm'] } } }`

**Comment by Romkond** [comment]
Oh... Yes, I inverted the syntax. Thank you.
