### ISSUE TITLE
Error: Path must be a string. Received undefined using Node 6.9

### ISSUE THREAD

**Issue by AlexZeitler** [dciccale/grunt-processhtml#109]
Using this `grunt-processhtml` config in my `Gruntfile`:

```
processhtml: {
      dist: {
        files: {
          'dest/index.html': ['index.html']
        }
      }
    }
```

Verbose output:
```
Running "processhtml:dist" (processhtml) task
Verifying property processhtml.dist exists in config...OK
Files: index.html -> dest/index.html
Options: process=false, data={}, templateSettings=null, includeBase=null, commentMarker="build", strip=false, recursive=false, customBlockTypes=[], environment="dist"
Warning: Path must be a string. Received undefined Use --force to continue.
```

I get this error using Node.js `6.9.5`, grunt `1.0.1` and grunt-processhtml `0.4.1`:
`Error: Path must be a string. Received undefined`.
Using Node `4.2.3` everything works fine.

**Comment by dciccale** [comment]
could you provide a full working example of the grunt file you are testing with? So I can replicate the issue as well.

Thanks

**Comment by dciccale** [comment]
No more data provided. Re-open if needed.
