### ISSUE TITLE
[Question/Feature Request] Is it possible to use this to include remote files?

### ISSUE THREAD

**Issue by McOmghall** [dciccale/grunt-processhtml#113]
For example, to include fonts/css/images remotely it'd be very convenient to just do the following:

```
<!-- build:css inline -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins&subset=latin,latin-ext" type="text/css">
<!-- /build -->
```

Same for `scripts` and other resources.

**Comment by dciccale** [comment]
Remote resources are not being parsed. I don't have much time to do this feature, and is the first time it is asked for it.

Feel free to open a Pull request if you would like to develop this feature.

However I think a feature would be interesting to support if more use cases (and people) needs it.

**Comment by McOmghall** [comment]
I think most of the work will need to be done on https://github.com/dciccale/node-htmlprocessor so i'll do the pull request there.
