### ISSUE TITLE
Inline external JS files

### ISSUE THREAD

**Issue by xMarkusSpringerx** [dciccale/grunt-processhtml#117]
Hey is there a possibility to inline external JS files?

```
<!-- build:js inline -->
<script src="https://test.com/test.min.js"></script>
<!-- /build -->
```

**Comment by dciccale** [comment]
Hi, this is not possible. I think this module is intended for local development where you would not inline remote code.
I think it would also add quite some complexity, what if the download fails or is blocked? what if there's no internet connection while developing or building on your ci, or the content is corrupted. maybe skip it and default to use <script> tag? it could be a modifier to allow remote files, but for now I think It should be straight forward for you to write a custom js function to download the remote file and insert it in a javascript tag in the head of the document.
