### ISSUE TITLE
How to replace multiple attributes?

### ISSUE THREAD

**Issue by message** [dciccale/grunt-processhtml#32]
Hi, i want to replace `rel` attribute also. Is it possible to replace two or more attributes? 

``` html
<!-- build:[href] /styles.min.css -->
<link rel="stylesheet/less" href="/app/styles/styles.less">
<!-- /build -->
```

**Comment by thomashigginbotham** [comment]
I have a similar need to replace multiple attributes. For example, setting the `src` and an `async` attribute on a script:

```
<!-- build:js /js/built.js -->
<script src="/src/require.js" data-main="/js/main"></script>
<!-- /build -->
```

Is there a way to accomplish that currently?

**Comment by kumorko** [comment]
same problem for me

**Comment by Smaug333** [comment]
Would be a very nix feature if supported

**Comment by dciccale** [comment]
@thomashigginbotham Why you don't include the `async` attribute already?

```html
<!-- build:js /js/built.js -->
<script src="/src/require.js" data-main="/js/main" async></script>
<!-- /build -->
```

Output:

```html
<script src="/js/built.js" data-main="/js/main" async></script>
```
