### ISSUE TITLE
enable attributes in block tag

### ISSUE THREAD

**Issue by endorama** [dciccale/grunt-processhtml#34]
Hello, thanks for this plugin :) 

I don't know if I'm missing something, but I couldn't find information about this...

I've an enhancement to propose: enable passing block arguments in the block tag.
For example:
```html
<!-- build:inline(css) css/style.css -->
  <link rel="stylesheet" type="text/css" href="css/style.css" />
<!-- /process -->
<!-- process:inline(js) js/script.js -->
  <script src="js/script.js" type="text/javascript" charset="utf-8"></script>
<!-- /process -->
```

In this way is possible to reuse code inside customBlocks avoiding duplicating the same code for little different things ( in this case the inline block puts the content of the file inline in the html ).

Maybe there is way to acheive this but currently I'm using a little hack :)

Thanks again

**Comment by dciccale** [comment]
Now by using `[attr]` blocktype you can achieve this.
