### ISSUE TITLE
build:css:my_target min.css does not work if you call it's target

### ISSUE THREAD

**Issue by genechan** [dciccale/grunt-processhtml#50]
If i call  the build target to min the css to a single link tag, it does not work. grunt processhtml:debug
However if i just call grunt processhtml with no target it will create the single link tag

        
            <link rel="stylesheet" href="files/ui/css/fonts.css">
            <link rel="stylesheet" href="files/ui/css/sprites.css">
            <link rel="stylesheet" href="files/ui/css/pages/homepage.css">                   
        
        
grunt file options
      debug: {
        files: [
          {
            expand:true,
            cwd:'files/',
            src:[
                  '*.html',
                  '**/*.html',
                  '!*.inc.html',
                  '!**/*.inc.html'
                ],
            dest:'../htdocs/'
          }
        ],
        options:{
          strip:true,
          data: {
            message: 'This is development environment'
          }          
        }
      }

**Comment by dciccale** [comment]
check again, this doesn't seem to be a bug on the plugin, target based tasks is a grunt thing
