### ISSUE TITLE
issue with newline character '\n' 

### ISSUE THREAD

**Issue by himajasuman** [dciccale/grunt-processhtml#56]
I am including processhtml blocks in index.html through my custom generator by appending each line with a newline character.

Ex:
'\n' +
''

I am including the above string and it appears like 

When I run processhtml, it is not including the script because 'content.indexOf(blockLine)' will be -1 as in the 'content' all the \r\n's are replaced with \n and in the 'blockLine' the \r\n's aren't replaced.

Can some body look into that issue. Please?

**Comment by dciccale** [comment]
closed no response, try a newer version it may be fixed.
