### ISSUE TITLE
Support for media="print"

### ISSUE THREAD

**Issue by atimmer** [dciccale/grunt-processhtml#58]
Currently media="print" is completely stripped and there is no way to include it.

Can you give a direction to how you would prefer this to be implemented? ea. In the HTML as an extra attribute, or as an option in the Gruntfile, or as auto detect the media attribute of the containing link tags. Then I can spin up a pull request.

**Comment by dciccale** [comment]
Now by using `[attr]` blocktype you can achieve this.
