### ISSUE TITLE
included only first file while proccessing

### ISSUE THREAD

**Issue by jovpet** [dciccale/grunt-processhtml#59]
I have a strange issue. Actually in my index.html everything works smooth but in my home.svg it doesn't.
In my home.svg.html I have multuple includes and only first one is proccessed.
here is the code sample:
<pre>
<code>
&lt;svg version=\&quot;1.1\&quot; id=\&quot;Layer_1\&quot; xmlns=\&quot;http://www.w3.org/2000/svg\&quot; xmlns:xlink=\&quot;http://www.w3.org/1999/xlink\&quot; x=\&quot;0px\&quot; y=\&quot;0px\&quot;<br />
 viewBox=\&quot;0 0 1600 978\&quot; enable-background=\&quot;new 0 0 1600 978\&quot; xml:space=\&quot;preserve\&quot;&gt;<br />
&lt;image overflow=\&quot;visible\&quot; width=\&quot;1600\&quot; height=\&quot;978\&quot; xlink:href=\&quot;data:image/png;base64,<br />
&lt;!-- build:include ../tmp/bg.b64.html --&gt;<br />
This will be replaced<br />
&lt;!-- /build --&gt;<br />
\&quot;&gt;<br />
&lt;/image&gt;<br />
&lt;image overflow=\&quot;visible\&quot; width=\&quot;207\&quot; height=\&quot;305\&quot; xlink:href=\&quot;data:image/png;base64,<br />
&lt;!-- build:include ../tmp/dizalica.b64.html --&gt;<br />
This will be replaced by dizalica<br />
&lt;!-- /build --&gt;<br />
***
</code>
</pre>
my grunt task is set to process recursively since I have those files in index.html but I have no idea why home.svg.html hasn't been processed properly.
here is my grunt.js file settings for processing:
<pre>
processhtml: {
      dev: {
        options: {
          process: true,
          recursive: true,
        },
        files: {
          'svg/home.svg': ['templates/home.svg.html'],
          'html/index.html': ['templates/index.html'],
        }
      },
    },
</pre>
 Any clues?

**Comment by juliandescottes** [comment]
I have a similar issue. 

When using recursive:true, only the first `include` of a file will be processed. 
When using recursive:false, all `include` are processed.

**Comment by juliandescottes** [comment]
I think the issue comes from the `include` method in node-htmlprocessor blocktypes.js 

    if (this.options.recursive) {
      fileContent = this.process(assetpath);
    } else {
      fileContent = fs.readFileSync(assetpath).toString();
    }

A new instance of HTMLProcessor should be used here I think.

**Comment by dciccale** [comment]
are getting any error? check that your files you want to exists exists in the path, this example is working perfectly:

`Gruntfile.js`
```js
module.exports = function (grunt) {
  'use strict';

  grunt.initConfig({
    processhtml: {
      prod: {
        options: {
          process: true,
          recursive: true
        },
        files: {
          'test.processed.html': ['test.html']
        }
      }
    }
  });

  grunt.loadNpmTasks('grunt-processhtml');

  grunt.registerTask('default', ['processhtml']);
};
```

`test.html`
```html
<!doctype html>
  <html>
    <head>
      <title>demo</title>
    </head>

    <body>
      <!-- build:include include.html -->
      <!-- /build -->
    </body>
</html>
```

`include.html`
```html
<h1>include1</h1>
<!-- build:include include2.html -->
<!-- /build -->
```

`include2.html`
```html
<h2>include2</h2>
```

`test.processed.html`
```html
<!doctype html>
  <html>
    <head>
      <title>demo</title>
    </head>

    <body>
      <h1>include1</h1>
<h2>include2</h2>
    </body>
</html>
```
