### ISSUE TITLE
Template variable including `$&` breaks build

### ISSUE THREAD

**Issue by yunntan** [dciccale/grunt-processhtml#60]
Hi,

I am pretty new to grunt, so this my be a mistake coming from me. But I have noticed this strange behaviour: when trying to include a variable containing the string `$&`, the generated output seem to actually `$&` this by the previous template comment bit. 
Here is an example of the config and the output:

### Template
```
 <!-- build:template
       <p><%= message %></p>
     /build -->
    <!-- build:template
      <p><%= test %></p>
    /build -->
```

### Grunt conf
```
processhtml: {
            options: {
                data: {
                    message: ' Hello ',
                    test: 'text_$&_text'
                }
            },
            dist: {
                files: {
                    'build/index.html': ['src/index.html']
                }
            }
        },
```

### Output
```
<p> Hello </p>
    <p>text_    <!-- build:template
      <p><%= test %></p>
    /build -->_text</p>
```
### Expected Output
```
<p> Hello </p>
<p>text_$&_text</p>
```

**Comment by dciccale** [comment]
This comes from a javascript thing http://stackoverflow.com/questions/9423722/string-replace-weird-behavior-when-using-dollar-sign-as-replacement

will fix it in next release
