### ISSUE TITLE
Template does not work when targeting specific task

### ISSUE THREAD

**Issue by jbarker4682** [dciccale/grunt-processhtml#63]
I am able to remove content from the page based on the target task

**example:**
```html
    <!-- build:remove:prod -->
    //...content to be removed
    <!-- /build -->
```
This works as intended, but I am NOT able to do the opposite using template

**example:**
```html
    <!-- build:template:prod
    //...content to 'un-comment' during 'prod' build only
    /build -->
```

results in:
```html
    <!-- build:template:prod
       //...content to be included -->
```

I  have also tried using the injected script block approach (per your example on the main page), but whenever I try this and set options.process = true, I get a GRUNT exception:
```html
    <!-- build:template
    <% if (environment === 'prod') { %>
    //...content to only include during 'prod' build
    <% } %>
    /build -->
```
results in error:
    **Running "processhtml:prod:prod" (processhtml) task
    Warning: Unexpected token ) Use --force to continue.**

Here is my relevant grunt file code
```javascript
    var _processHtml = {
      prod: {
        files: {
          'build/<%= grunt.task.current.args[0] %>/app/index.html': ['build/<%= grunt.task.current.args[0] %>/app/index.html']
        }
      }
    };
```

I manually run the processHtml task from within my main build task using the following line:
```javascript
    grunt.task.run("processhtml:prod:prod");
```

Any help would be greatly appreciated.

Thanks!

Josh

**Comment by dciccale** [comment]
The task you should run is `processhtml:prod`

**Comment by jbarker4682** [comment]
Actually, the second ":prod" is the target environment... I could have hard-coded the environment, but I wanted to keep the flexibility and follow the existing convention.

Anyhow, I tried every combination I could, including what you listed above.  did not help. I ended-up having to switch to grunt-targethtml instead.

**Comment by dciccale** [comment]
I am not sure of what was the problem, check the tests there are plenty of tests targeting many different configurations.

**Comment by dciccale** [comment]
The target should be only one, so `processhtml:prod` is the correct way.

**Comment by jbarker4682** [comment]
The first "prod" is the task target, the second ":prod" is a command parameter, which is used to define the build folder... it could be anything (dev, qa, beta, etc...), and is used by this line: <%= grunt.task.current.args[0] %>/app/index.html. Like I said, i could have hard-coded this, but did not want to restrict myself form being able to pass an alternate build folder name
