### ISSUE TITLE
Can we do a link attribute rel configuration?

### ISSUE THREAD

**Issue by vance** [dciccale/grunt-processhtml#66]
Howdy,
Trying to figure out how to configure for import in a link tag. So how to make this:
```
        <!-- build:[href] components -->
        <!-- /build -->
```

do this:

```
<link rel="import" href="../../polymer-components/src/components/input/some-input.html">
```

**Comment by vance** [comment]
I'm getting closer:

```
 <!-- build:process components -->
        <script rel="import" href="<%= ACTUAL-SOURCE %>">
        </script>
        <!-- /build -->
```

how do i replace  ACTUAL-SOURCE with the url specified in the gruntfile?

**Comment by dciccale** [comment]
```html
<!-- build:[href] components/ -->
  <link rel="import" href="../../polymer-components/src/components/input/some-input.html">
<!-- /build -->
```

**Comment by vance** [comment]
When I do that, i get `href=""` how do i get it to insert the path from the config/path scanner into the href? I can't hard code it as you show it, I thought that was the whole point of using html build.
