### ISSUE TITLE
Inline template blocks

### ISSUE THREAD

**Issue by goodpixels** [dciccale/grunt-processhtml#67]
Hi there,

The template blocks are super cool, but I need to use them **inline** rather then after the new line.

So instead of this:

```
<h3>
<!-- build:template
<%= config.siteTitle %>
/build -->
</h3>
```

I want to do this:

```
<h3><!-- build:template <%= config.siteTitle %> /build --></h3>
```

or this:

```
<h3><!-- build:template --><%= config.siteTitle %><!-- /build --></h3>
```

Any ideas?

Cheers,
John

**Comment by dciccale** [comment]
For now there is no support for doing any processing inline.. this is a requested feature, needs to be done in a global level.

I guess you could do this for now:

```html
<!-- build:template
<h3><%= config.siteTitle %><h3>
/build -->
```

See the `<h3>` tag is inside the process block.

**Comment by goodpixels** [comment]
right. this is some kind of workaround, but doesn't fully solve my issue.

it does generate correct code in the output file, but if i view the source file in the browser, the code inside that comment block obviously won't render.

when do you think is the earliest this could implemented?

i think it would be a great feature to have, especially because other plugins seem to have implemented it: https://github.com/spatools/grunt-html-build

thanks,
John

**Comment by dciccale** [comment]
i don't see that grunt-html-build supports inline matching
