### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by danielsoner** [dciccale/grunt-processhtml#74]
Hi,
I have been trying to process a lot of files with your plugin (the latest version), but after about half of them are processed, I get this message: Warning: Maximum call stack size exceeded Use --force to continue.

I have found that if I change in the file processhtml.js this: next(null); with this: setTimeout(function(){next(null);},20); that it works.

Can you please have a look at it? It would be really awesome if I can use your very helpful plugin.

Thank you!

**Comment by dciccale** [comment]
how many files are you trying to process?

and what block types are you processing? js, css, template, include, others? I haven't tested so many files I don't know how it behaves give me some insight

**Comment by dciccale** [comment]
fixed now, calling process.nextTick. processed 1000 files and it was pretty fast

**Comment by danielsoner** [comment]
Great!
