### ISSUE TITLE
Is build:js FILENAME.js supposed to export the contained files into FILENAME.js?

### ISSUE THREAD

**Issue by dotherightthing** [dciccale/grunt-processhtml#76]
Apologies, but I'm confused as to what this plugin actually does ;-)

in `myfile.html`:

        
        <script src="../../../dev/modules/m-call-to-action/ct__stickyFooter.js"></script>
        <script src="../../../../bower_components/jquery-waypoints/waypoints.js"></script>
        

Should this plugin concatenate `ct__stickyFooter.js` and `waypoints.js` into `FILENAME.js`?

When I run this I just get the two `<script>` tags replaced by the existing contents of `FILENAME.js` - i.e `ct__stickyFooter.js` and `waypoints.js` are 'lost' in the process.

Is concatenation something I need to handle separately?

My Gruntfile:

    processhtml: {
      options: {
        process: true
      },
      scripts: {
        options: {
          force: true // allow overwriting of templates
        },
        files: [
          {
            expand: true,
            cwd: "<%= project.build.html_templates %>",
            src: [
              "*.html"
            ],
            dest: "<%= project.build.html_templates %>/"
          }
        ]
      }
    },

Thanks.

**Comment by dciccale** [comment]
this plugin doesn't involves in what you do with your files. you need to provide a way to concat and minify your files. what this plugin does is replacing

```html
   <!-- build:js FILENAME.js -->
    <script src="../../../dev/modules/m-call-to-action/ct__stickyFooter.js"></script>
    <script src="../../../../bower_components/jquery-waypoints/waypoints.js"></script>
    <!-- /build -->
```

with 

```html
    <script src="FILENAME.js"></script>
```

You need to generate the `FILENAME.js` file. using something like grunt-contrib-uglify and/or grunt-contrib-concat

cheers
