### ISSUE TITLE
How do you build html file that exist in a subfolder? 

### ISSUE THREAD

**Issue by guntherkoo** [dciccale/grunt-processhtml#79]
All the root .html files get built with include but the subfolder doesn't have the same effect. Need help! :)

This is my Grunt.js file: 

processhtml: {
 dist: {
	options: {
		process: true
		},
		files: [{
			expand: true,
			cwd: 'app/',
			src: ['**/*.html'],
			dest: 'public/',
			ext: '.html'
		}]
	}
},

Thanks in advance!

**Comment by dciccale** [comment]
what about tis `**/*.html` ?

**Comment by guntherkoo** [comment]
Nah, it still doesn't seem to read the  file for me.. :(

**Comment by guntherkoo** [comment]
Seems to only be reading only the .html files in the root but not any in the subfolders.. please help!

**Comment by dciccale** [comment]
try passing the `recursive` option

```
dist: {
options: {
recursive: true,
process: true
},
``

**Comment by dciccale** [comment]
if this doesn't work, please explain better what's the issue, are you trying to include nested files? or just process through subfolders?

try give an example of the issue

**Comment by guntherkoo** [comment]
I tried that as well, so basically what I'm trying to do is to include the header and footer for this website I'm building. HTML files that exist on the root of the app/ works with including header.html and footer.html but any HTML files that exist inside a folder isn't getting the included tag files like header.html and footer.html after I run the build grunt task. 

Since the HTML file is inside a folder, I've tried changing the include tag to be /include/header.html but that still isn't working for me.

**Comment by guntherkoo** [comment]
Hi @dciccale, any idea on how to fix this? Sorry to bother you, just want to get this working :)

**Comment by guntherkoo** [comment]
@dciccale I just figured it out! Maybe something you want to include in your documentation. You need to include the option:includeBase <dir> in order for subfolder .html items to be built with processhtml. 

Removing the folder the include files are in, just having 

Hope that can help the next person who comes across this issue. 

Thanks for your help none the less!

**Comment by dciccale** [comment]
ok thanks!
