### ISSUE TITLE
Unexplained file size increase

### ISSUE THREAD

**Issue by mathiasleroy** [dciccale/grunt-processhtml#80]
Hello,

My input html file is 75kb (2178 lines)

I combine several css and js lines into one.

	
        ...
	

	
        ...
	

The output html file is 114kb (2154 lines)

How come?
No text was added, only removed.
Maybe the encoding changed?

**Comment by dciccale** [comment]
i don't think changing the encoding could add 39kb to your file.

grunt-processhtml doesn't add anything to your files, it just process them.

doesn't look like an issue of the plugin please review your code
