### ISSUE TITLE
build:template:target doesn't honor target

### ISSUE THREAD

**Issue by wlingke** [dciccale/grunt-processhtml#83]
I tried to process an html with:

```
<!-- build:template:dist
<p>Hello, <%= name %></p>
/build -->
```

and ran it with the grunt task: `grunt processhtml:staging` and it compiled that block

**Comment by dciccale** [comment]
paste the relevant part of your gruntfile pls

**Comment by wlingke** [comment]
```
        processhtml: {
            options: {
                strip: true
            },
            dist: {
                files: {
                    "production/views/index.html": ['views/index.html']
                }
            },
            staging: {
                files: {
                    "production/views/index.html": ['views/index.html']
                }
            }
        },
```

I tested this with a `build:css:dist` and the target on the `css` build worked as expected (ie worked when i called `grunt processhtml:dist` and skipped it when I called `grunt processhtml:staging`)

**Comment by dciccale** [comment]
try removing `strip: true`

if you run `grunt processhtml:staging` with strip set to true, the comment tags of  `<!-- build:template:dist` will be removed.

if you do need the strip option, apply it locally

```
        processhtml: {
            dist: {
                options: {
                    strip: true
                },
                files: {
                    "production/views/index.html": ['views/index.html']
                }
            },
            staging: {
                files: {
                    "production/views/index.html": ['views/index.html']
                }
            }
        }
```

**Comment by dciccale** [comment]
i think the previous comment fixes your issue. feel free to reopen if you continue having some issue.
