### ISSUE TITLE
Paths with PHP in them - escape or ignore?

### ISSUE THREAD

**Issue by aleross** [dciccale/grunt-processhtml#86]
Hi,

I have a bit of PHP which selects which JS file to load based on user information:

```
<!-- release /js/<?php echo $app; ?>.min.js -->
<script src="/js/<?php echo $app; ?>.js"></script>
<!-- /build -->
```

The problem is, the release path comes out `undefined`. Is it possible to ignore the PHP and pass it through after processing the file?

I can get around it by coding out all of the cases, but this isn't ideal:

```
        <?php if ($app === 'case1') { ?>
            <!-- build:js:release /js/case1.min.js -->
            <script src="/js/case1.js"></script>
            <!-- /build -->
        <?php } elseif ($app === 'case2') { ?>
            <!-- build:js:release /js/case2.min.js -->
            <script src="/js/case2.js"></script>
            <!-- /build -->
        <?php } else { ?>
            <!-- build:js:release /js/case3.min.js -->
            <script src="/js/case3.js"></script>
            <!-- /build -->
        <?php } ?>
```

**Comment by dciccale** [comment]
you can't read php variables from javascript, you'll need to first process the php and process the output with the plugin

**Comment by aleross** [comment]
I think you misunderstand... I want the PHP to be treated as a string by `grunt-processhtml`. Instead, the plugin throws away the entire src and replaces it with `undefined`.

**Comment by dciccale** [comment]
i see, the regexp to match the asset was intended to match a string with no spaces. https://github.com/dciccale/node-htmlprocessor/blob/master/lib/parser.js#L36

i think we could adapt it a bit to match more cases, will explore the idea

**Comment by dciccale** [comment]
@aleross feel free to work it out yourself, just play around with the regex and run the test `npm test`

**Comment by aleross** [comment]
Thanks I'll take a look when I have some time

**Comment by dciccale** [comment]
I think this will be quite hard

http://stackoverflow.com/a/1732454/194630

I think the only way to address this would be using an html parser... but that implies a re-write of https://github.com/dciccale/node-htmlprocessor

**Comment by dciccale** [comment]
a pr is welcome to address this, I don't have the time anymore. feel free to continue, thx
