### ISSUE TITLE
Warning: Invalid regular expression message from 0.3.9 and next versions

### ISSUE THREAD

**Issue by joserg** [dciccale/grunt-processhtml#93]
Warning: Invalid regular expression from version 0.3.8 to 0.3.9 and next

The principal diference from 0.3.8 to 0.3.9 and next that we can see is
 the use of "htmlprocessor": "0.2.0"
see commit 0beab4f6feb34e87b6ba3a884e066986ae0f0590

when we use 0.3.8 all work ok, but using 0.3.9 and next we obtain things like this:

Warning: Invalid regular expression: /
        
        <style type="text/css">
            #cloak {
                display: table;
                position: fixed;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                z-index: 9999;
            }
        </style>
        /: Nothing to repeat Use --force to continue.

**Comment by dciccale** [comment]
thanks for contributing!, I'll be checking the issue and come back soon

**Comment by dciccale** [comment]
i just publish a new version including node-htmlprocessor@0.2.2 with a possible fix https://github.com/dciccale/node-htmlprocessor/pull/22

let me know if the issue is still there

**Comment by dciccale** [comment]
closing for lack of response. re-open if needed I will gladly help :)
