### ISSUE TITLE
is it possible to not specify files?

### ISSUE THREAD

**Issue by vlrprbttst** [dciccale/grunt-processhtml#95]
is it possible to not specify files i want to process? i want all my html files to be processed as they all have includes but this configuration doesn't work:

```
        processhtml: {
            dev: {
                files: {
                    '_dev/*.html': ['_src/*.html']
                }
            }
        },
```

is there a way to tell it that, if i change index in _src, process that and produce the final file with the same filename in _dev?

thanks! this is a great grunt module!

**Comment by dciccale** [comment]
did you solved your issue?

that's [grunt configuration](http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically). read the following issues all touching the same topic

#29
#33
#45
#47

**Comment by vlrprbttst** [comment]
yes thanks, i wanted to delete the issue (which is not an issue of the module) but couldn't :) thanks!

**Comment by surjithctly** [comment]
@dciccale Please add a sample in the Readme. Even I was about to open a new issue just because it's not outlined in the documentation. 

```js
processhtml: {
            dist: {
                files: [{
                    expand: true, // Enable dynamic expansion.
                    cwd: './', // Src matches are relative to this path.
                    src: ['*.html', 'views/**/*.html'], // Actual pattern(s) to match.
                    dest: 'dist/', // Destination path prefix.
                }],
            }
        },
```
