### ISSUE TITLE
processing html files generated before with grunt-generator and multiple handlebar partials not working

### ISSUE THREAD

**Issue by odoell** [dciccale/grunt-processhtml#99]
hello,

i have some html files that are not processed. These html files are generated with grunt-generator and handlebar templates before processing them.
 Unfortunately i cannot add my project .zip. Github denies my file. So you can get it here:

[DROPBOX LINK](https://dl.dropboxusercontent.com/u/95142200/src-v0.0.4-issue.ZIP)

In the project files you will find a gruntfile with following tasks to perform, to replicate my issue:

grunt dev and grunt build: after that you find the affected files in server and dist folder.
from the server html files the dist html files are processed.

There are generated 3 html files in the dist folder, demoelements and stickyfooter is working, but index.html is not processed if i uncomment more than one handlebar partial in index.hbs. crosschecked if included html is valid...

if i add the html from the handlebar partials direct into the index,hbs, generate the html file and process afterwards, it works. if i replace the html in the index.hbs with the handlebar partials, index.html is not processed correctly

Oliver

**Comment by dciccale** [comment]
i wasn't able to install the dependencies, .jshintrc is missing and .postinstall.js and maybe other stuff is failing too.

what block type is failing for you? is it the <-- build:include --> ? or which one?

**Comment by dciccale** [comment]
how's it going over there?

**Comment by dciccale** [comment]
feel free to re-open so we can review this further
